-- Fix: Add Étape 6 status values to accreditation_requests_status_check constraint
-- New values: MANDATES_PREPARATION, MANDATES_PENDING_CD, MANDATES_CD_MODIFICATION, MANDATES_SENT_TO_TEAM,
--   MISSION_ORDERS_PENDING, MISSION_ORDERS_PENDING_DT, MISSION_ORDERS_PENDING_DG, MISSION_ORDERS_SENT,
--   EVALUATION_PLAN_PREPARATION, EVALUATION_PLAN_PENDING_RA, EVALUATION_PLAN_RA_APPROVED,
--   EVALUATION_PLAN_PENDING_CD, EVALUATION_PLAN_VALIDATION, EVALUATION_PLANNED

ALTER TABLE accreditation_requests DROP CONSTRAINT IF EXISTS accreditation_requests_status_check;

ALTER TABLE accreditation_requests ADD CONSTRAINT accreditation_requests_status_check CHECK (
  status::text = ANY(ARRAY[
    'DRAFT','SUBMITTED','AWAITING_REGISTRATION_FEE','PENDING_PAYMENT','PAYMENT_PROOF_SUBMITTED','PAYMENT_COMPLETED','ASSIGNED_TO_RA',
    'RECEIVABILITY_STUDY','RECEIVABILITY_PENDING_CD_REVIEW','RECEIVABLE','NOT_RECEIVABLE','RECEIVABILITY_CORRECTION','RECEIVABILITY_RESUBMITTED',
    'PRELIMINARY_VISIT_PROPOSED','PRELIMINARY_VISIT_ACCEPTED','PRELIMINARY_VISIT_DECLINED','PRELIMINARY_VISIT_SCHEDULED','PRELIMINARY_VISIT_COMPLETED','PRELIMINARY_VISIT_REPORT_PENDING','PROCESS_SUSPENDED_OBSTACLES',
    'QUOTATION_PREPARATION','QUOTATION_SENT_TO_DAG','QUOTATION_APPROVED_BY_DAG','CONVENTION_PREPARATION','QUOTATION_CONVENTION_PENDING_CD','QUOTATION_CONVENTION_CD_MODIF','QUOTATION_SENT_TO_OEC','QUOTATION_OEC_REMINDER','QUOTATION_VALIDATED','QUOTATION_EXPIRED',
    'TEAM_DESIGNATION','TEAM_SENT_TO_CD','TEAM_CD_APPROVED','TEAM_CD_CHANGES_REQUESTED','TEAM_SENT_TO_OEC','TEAM_DATE_REFUSED','TEAM_MEMBER_RECUSED','TEAM_RECUSED','TEAM_RECUSATION_INVALID','TEAM_VALIDATED',
    'DOC_REVIEW_AWAITING_FEE','DOC_REVIEW_FEE_PENDING_PAYMENT','DOC_REVIEW_PAYMENT_SUBMITTED','DOC_REVIEW_PAYMENT_VALIDATED','DOC_REVIEW_IN_PROGRESS','DOC_REVIEW_RESULTS_SUBMITTED','DOC_REVIEW_RESULTS_SENT_TO_CD','DOC_REVIEW_RESULTS_SENT_TO_OEC','AWAITING_OEC_DOC_RESPONSE','DOC_REVIEW_CD_DECISION','DOCUMENTARY_REVIEW_COMPLETED','DOCUMENTARY_REVIEW','DOCUMENTARY_REVIEW_DEFICIENCIES',
    'MANDATES_PREPARATION','MANDATES_PENDING_CD','MANDATES_CD_MODIFICATION','MANDATES_SENT_TO_TEAM','MISSION_ORDERS_PENDING','MISSION_ORDERS_PENDING_DT','MISSION_ORDERS_PENDING_DG','MISSION_ORDERS_SENT','EVALUATION_PLAN_PREPARATION','EVALUATION_PLAN_PENDING_RA','EVALUATION_PLAN_RA_APPROVED','EVALUATION_PLAN_PENDING_CD','EVALUATION_PLAN_VALIDATION','EVALUATION_PLANNED',
    'EVALUATION_IN_PROGRESS','EVALUATION_COMPLETED',
    'AWAITING_ACTION_PLANS','ACTION_PLANS_EVALUATION','ACTION_PLANS_IMPLEMENTATION','COMPLEMENTARY_EVALUATION_NEEDED','COMPLEMENTARY_EVALUATION_PLANNED','COMPLEMENTARY_EVALUATION_PROGRESS','GAPS_RESOLVED',
    'REPORT_DRAFTING','REPORT_VALIDATION','REPORT_VALIDATED',
    'CAS_PREPARATION','CAS_SCHEDULED','CAS_DECISION_GRANT','CAS_DECISION_REFUSAL','CAS_DECISION_POSTPONEMENT',
    'CERTIFICATE_PREPARATION','CERTIFICATE_ISSUED',
    'ACTIVE','SUSPENDED','WITHDRAWN','CLOSED',
    'SURVEILLANCE_SCHEDULED','SURVEILLANCE_IN_PROGRESS','SURVEILLANCE_COMPLETED'
  ])
);
