-- Fix: Add Étape 7 & 8 status values to accreditation_requests_status_check constraint
-- New Étape 7 values: EVALUATION_OPENING_MEETING, EVALUATION_ONGOING, EVALUATION_CONSENSUS,
--   EVALUATION_CLOSING_MEETING, EVALUATION_GAPS_SENT_TO_OEC, EVALUATION_OEC_REVIEW,
--   EVALUATION_OEC_ALL_ACCEPTED, EVALUATION_DOCS_TRANSMITTED
-- New Gap statuses: SENT_TO_REE, KEPT_BY_REE, DISCARDED_BY_REE, SENT_TO_OEC, OEC_ACCEPTED, OEC_REFUSED

ALTER TABLE accreditation_requests DROP CONSTRAINT IF EXISTS accreditation_requests_status_check;

ALTER TABLE accreditation_requests ADD CONSTRAINT accreditation_requests_status_check CHECK (
  status::text = ANY(ARRAY[
    'DRAFT','SUBMITTED','AWAITING_REGISTRATION_FEE','PENDING_PAYMENT','PAYMENT_PROOF_SUBMITTED','PAYMENT_COMPLETED','ASSIGNED_TO_RA',
    'RECEIVABILITY_STUDY','RECEIVABILITY_PENDING_CD_REVIEW','RECEIVABLE','NOT_RECEIVABLE','RECEIVABILITY_CORRECTION','RECEIVABILITY_RESUBMITTED',
    'PRELIMINARY_VISIT_PROPOSED','PRELIMINARY_VISIT_ACCEPTED','PRELIMINARY_VISIT_DECLINED','PRELIMINARY_VISIT_SCHEDULED','PRELIMINARY_VISIT_COMPLETED','PRELIMINARY_VISIT_REPORT_PENDING','PROCESS_SUSPENDED_OBSTACLES',
    'QUOTATION_PREPARATION','QUOTATION_SENT_TO_DAG','QUOTATION_APPROVED_BY_DAG','CONVENTION_PREPARATION','QUOTATION_CONVENTION_PENDING_CD','QUOTATION_CONVENTION_CD_MODIF','QUOTATION_SENT_TO_OEC','QUOTATION_OEC_REMINDER','QUOTATION_VALIDATED','QUOTATION_EXPIRED',
    'TEAM_DESIGNATION','TEAM_SENT_TO_CD','TEAM_CD_APPROVED','TEAM_CD_CHANGES_REQUESTED','TEAM_SENT_TO_OEC','TEAM_DATE_REFUSED','TEAM_MEMBER_RECUSED','TEAM_RECUSED','TEAM_RECUSATION_INVALID','TEAM_VALIDATED',
    'DOC_REVIEW_AWAITING_FEE','DOC_REVIEW_FEE_PENDING_PAYMENT','DOC_REVIEW_PAYMENT_SUBMITTED','DOC_REVIEW_PAYMENT_VALIDATED','DOC_REVIEW_IN_PROGRESS','DOC_REVIEW_RESULTS_SUBMITTED','DOC_REVIEW_RESULTS_SENT_TO_CD','DOC_REVIEW_RESULTS_SENT_TO_OEC','AWAITING_OEC_DOC_RESPONSE','DOC_REVIEW_CD_DECISION','DOCUMENTARY_REVIEW_COMPLETED','DOCUMENTARY_REVIEW','DOCUMENTARY_REVIEW_DEFICIENCIES',
    'MANDATES_PREPARATION','MANDATES_PENDING_CD','MANDATES_CD_MODIFICATION','MANDATES_SENT_TO_TEAM','MISSION_ORDERS_PENDING','MISSION_ORDERS_PENDING_DT','MISSION_ORDERS_PENDING_DG','MISSION_ORDERS_SENT','EVALUATION_PLAN_PREPARATION','EVALUATION_PLAN_PENDING_RA','EVALUATION_PLAN_RA_APPROVED','EVALUATION_PLAN_PENDING_CD','EVALUATION_PLAN_VALIDATION','EVALUATION_PLANNED',
    'EVALUATION_IN_PROGRESS','EVALUATION_OPENING_MEETING','EVALUATION_ONGOING','EVALUATION_CONSENSUS','EVALUATION_CLOSING_MEETING','EVALUATION_GAPS_SENT_TO_OEC','EVALUATION_OEC_REVIEW','EVALUATION_OEC_ALL_ACCEPTED','EVALUATION_DOCS_TRANSMITTED','EVALUATION_COMPLETED',
    'AWAITING_ACTION_PLANS','ACTION_PLANS_EVALUATION','ACTION_PLANS_IMPLEMENTATION','COMPLEMENTARY_EVALUATION_NEEDED','COMPLEMENTARY_EVALUATION_PLANNED','COMPLEMENTARY_EVALUATION_PROGRESS','GAPS_RESOLVED',
    'REPORT_DRAFTING','REPORT_VALIDATION','REPORT_VALIDATED',
    'CAS_PREPARATION','CAS_SCHEDULED','CAS_DECISION_GRANT','CAS_DECISION_REFUSAL','CAS_DECISION_POSTPONEMENT',
    'CERTIFICATE_PREPARATION','CERTIFICATE_ISSUED',
    'ACTIVE','SUSPENDED','WITHDRAWN','CLOSED',
    'SURVEILLANCE_SCHEDULED','SURVEILLANCE_IN_PROGRESS','SURVEILLANCE_COMPLETED'
  ])
);

-- Add gap status constraint (or update if exists)
ALTER TABLE gaps DROP CONSTRAINT IF EXISTS gaps_status_check;

ALTER TABLE gaps ADD CONSTRAINT gaps_status_check CHECK (
  status::text = ANY(ARRAY[
    'IDENTIFIED','SENT_TO_REE','KEPT_BY_REE','DISCARDED_BY_REE','SENT_TO_OEC','OEC_ACCEPTED','OEC_REFUSED',
    'AWAITING_ACTION_PLAN','PLAN_SUBMITTED','PLAN_ACCEPTED','PLAN_REJECTED',
    'IMPLEMENTATION','EVIDENCE_PROVIDED','PENDING_VERIFICATION','RESOLVED','NEEDS_COMPLEMENTARY_EVAL'
  ])
);

-- Add missing columns to gaps table if not exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='created_by_id') THEN
    ALTER TABLE gaps ADD COLUMN created_by_id BIGINT REFERENCES users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='sent_to_ree') THEN
    ALTER TABLE gaps ADD COLUMN sent_to_ree BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='sent_to_ree_date') THEN
    ALTER TABLE gaps ADD COLUMN sent_to_ree_date TIMESTAMP;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='kept_by_ree') THEN
    ALTER TABLE gaps ADD COLUMN kept_by_ree BOOLEAN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='ree_modified_description') THEN
    ALTER TABLE gaps ADD COLUMN ree_modified_description TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='ree_modified_evidence') THEN
    ALTER TABLE gaps ADD COLUMN ree_modified_evidence TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='sent_to_oec') THEN
    ALTER TABLE gaps ADD COLUMN sent_to_oec BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='sent_to_oec_date') THEN
    ALTER TABLE gaps ADD COLUMN sent_to_oec_date TIMESTAMP;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='oec_accepted') THEN
    ALTER TABLE gaps ADD COLUMN oec_accepted BOOLEAN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='oec_refusal_reason') THEN
    ALTER TABLE gaps ADD COLUMN oec_refusal_reason TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gaps' AND column_name='oec_response_date') THEN
    ALTER TABLE gaps ADD COLUMN oec_response_date TIMESTAMP;
  END IF;
END $$;

-- Add missing columns to evaluation_notes table if not exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='evaluation_notes' AND column_name='content') THEN
    ALTER TABLE evaluation_notes ADD COLUMN content TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='evaluation_notes' AND column_name='section') THEN
    ALTER TABLE evaluation_notes ADD COLUMN section VARCHAR(255);
  END IF;
END $$;
